version: '3.8'

services:
  fastapi-web:
    build:
      context: .
      dockerfile: app.dockerfile
    depends_on:
      - celery
    volumes:
      - .:/app
    networks:
      - vidyo

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - vidyo

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
    networks:
      - vidyo

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - vidyo

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-web
      - celery
      - rabbitmq
    ports:
      - '4000:80'
    networks:
      - vidyo

networks:
  vidyo:
    driver: bridge
